version: 1
workflows:
  version: 1
  test:
    jobs:
      - test-pep8
      - test-py36
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
  test-pep8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -epep8
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -epy36
